### ISSUE TITLE
[info>] Xiaomi Mi Temperature sensor can't be flashed anymore OTA

### ISSUE THREAD

**Issue by hokreb** [revk/ESP-Faikin#301]
Hi revk, 

I just have gotten Xiaomi Mi Temperature sensor to connect to the faikin modul, 
unfortunately they have gotten a new firmware from xiaomi, which prevents to be flashed 
with the OTA tool (telink). The only way to flash them is by wire (see here a link, where the problem is discussed and 
described, how to flash by usb: https://github.com/atc1441/ATC_MiThermometer/issues/298)

**Comment by revk** [comment]
That's a bugger.

**Comment by PianSom** [comment]
Odd. I just this week had 3 delivered from Aliexpress in China, and all flashed fine using Edge. 

[Here](https://www.aliexpress.com/item/1005001583361057.html?) is the item I purchased.

Maybe I got an end of batch?

**Comment by revk** [comment]
Thanks for the info, shame.
