### ISSUE TITLE
[BUG] "on/off" icon isn't displayed correctly by a web browser

### ISSUE THREAD

**Issue by Sonic-Amiga** [revk/ESP-Faikin#322]
I see you've switched from text to icons again; I understand that it should be a standard on/off symbol, but at least on Windows browsers can't render it:
![image](https://github.com/revk/ESP32-Faikin/assets/48695031/d5092968-103f-4c76-ae13-cc3909d9f46e)
And that's not Firefox-specific issue; i tried Edge; it also looks like a square

**Comment by Sonic-Amiga** [comment]
Tested on Firefox for Android; the same thing

**Comment by revk** [comment]
There is a setting now. Have a look.

**Comment by Sonic-Amiga** [comment]
You mean "noicons" setting ? I know, but it looks boring without all the icons.

**Comment by revk** [comment]
You want some of the icons but not all!!!

Isn't Unicode fun.

**Comment by Sonic-Amiga** [comment]
Yes. And i'd say showing text instead of this particular icon should be the default; because i suggest there are plenty of users with not-so-cutting-edge systems around; who will see the empty square. It definitely feels like a bug, even to me, who knows the drill.

I replaced icon back with text in my port; but yours is subject too; plus it's yet another unwanted diff. I'd like to be as upstream as possible, this simplifies things a lot.  I even have a dream of complete merge; but currently amount of #ifdef's would still be rather large; you wouldn't be happy with such a merge, neither it would be easy to maintain.
