### ISSUE TITLE
Rename 'ESP32' to 'ESP'

### ISSUE THREAD

**Issue by Sonic-Amiga** [revk/ESP-Faikin#324]
Would you mind renaming the folder within your source tree ? I did that when updating my port back in February; because it felt wrong to reference ESP32 in 8266 port. But now i cannot cherry-pick because of path difference; i have to compare files side-by-side and pick changes manually. It's very inconvenient process.

**Comment by Sonic-Amiga** [comment]
Sorry, what does this mean ? "No i won't rename" ?

**Comment by revk** [comment]
Did you look at the name of the project now?

**Comment by revk** [comment]
Oh...

**Comment by revk** [comment]
Done.

**Comment by Sonic-Amiga** [comment]
Thank you, i reply in evenings, just made it to the keyboard. Yes, i meant exactly this - renaming a directory inside the project, not the project itself. Because git only sees and cares about the former. Now i can do cherry-picks back and forth again.
