### ISSUE TITLE
[FEATURE] MQTT Topic name

### ISSUE THREAD

**Issue by lorbetzki** [revk/ESP-Faikin#325]
Hello,

at the moment we have this mqtt situation:

command/\<hostname>
setting/\<hostname> 
event/\<hostname> 
info/\<hostname> 
error/\<hostname>
\<mac of faikin> # livestatus
homeassistant/*/\<mac>

I would appreciate it if you could specify a sendtopic by yourself instead of hostnames or mac. This would simplify filtering immensely.

for example

\<topic>/command/
\<topic>/setting/ 
\<topic>/event/ 
\<topic>/info/ 
\<topic>/error
\<topic>/livestatus/
homeassistant/*/\<topic>/

what would you think of this?

**Comment by revk** [comment]
This would be a RevK library feature not Faikin specific.

Not impossible. Would need to be a setting.

**Comment by revk** [comment]
Library update in latest beta, new setting, please try.
